name: Testing new pull requests
on:
  pull_request:
    branches: [ dev ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.12.0
      - run: npm ci
      - run: npm test